### ISSUE TITLE
How is pubsub implemented?

### ISSUE THREAD

**Issue by sordina** [patchbay-pub/patchbay-simple-server#4]
I'm trying to make a Haskell version of the simple-server and have a working version here:

https://gist.github.com/sordina/52e07f34abd6effd6dbbf5c6a782658a

However after reading the intro, I saw that the web-hosting capability is provided via 'pubsub' functionality. I'm trying to figure out where this is implemented so I can see how patchbay implements the feature, but I can't find any reference to 'pubsub' in the organisation:

https://github.com/search?q=org%3Apatchbay-pub+pubsub&type=Code

Let me know if I've missed something obvious!

**Comment by anderspitman** [comment]
Hi @sordina,

A couple things:

1) This server isn't a full implementation of the protocols running on patchbay.pub. It's simply meant as a starting point for others to understand the core mechanism for the MPMC part, which I think is the most interesting. The production server is currently still closed-source, but I want to open source it and am actively considering my options. I am very against vendor lock-in and open sourcing is one of the best defenses against that.

2) The web hosting is actually implemented without pubsub, so you're probably really close to having it working! I don't know Haskell, so I can't tell by glancing at your code how correct it is.

Can you point me to the part of the intro that indicated you need pubsub? I can probably update it to be more clear.

**Comment by sordina** [comment]
Hi @anderspitman ,

Ah my mistake, I didn't read carefully enough! There are many references to pubsub, but not in the web-hosting section.

Am I correct in assuming that this:

```
If you set the pubsub=true query parameter, like this:

curl https://patchbay.pub/z2ss-mrx1?pubsub=true -d "Hi there"
      
the request uses the channel in a different mode. GETs act similar to before, but POSTs become non-blocking, and will broadcast messages to all blocked pubsub consumers, not just the first one. As the name suggest, this models the PubSub pattern.
```

... means that you must spawn the GETs before you post? But then, how do the GETs know to fork the channel if the pubsub param is set in the POST? Or do both producers and consumers need to set the param?

**Comment by anderspitman** [comment]
Yep you've got it exactly. If there aren't any subscribers, pubsub messages are just thrown away. And yes, you have to set pubsub=true on both the GETs and POSTs.

Note that since unhandled messages are dropped, if you can't miss any messages, you have 2 options:

1. Have multiple subscribers listening and coordinating together. You need enough such that there's always at least one attached to patchbay.pub at any moment, and can keep up with the rate of your publisher(s).

2. Set persist=true to receive every message on the same subscriber, and use an application layer protocol (such as server sent events, which is what I do with the public chat) to split incoming messages.

**Comment by sordina** [comment]
Thanks so much for the insight!

Happy to close the issue if you like!

**Comment by anderspitman** [comment]
No prob
